DROP TABLE IF EXISTS food_history;
CREATE TABLE food_history(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	_date TEXT NOT NULL,
	breakfast INTEGER NOT NULL,
	dinner INTEGER NOT NULL,
	guest_breakfast INTEGER NOT NULL ,
    guest_dinner INTEGER NOT NULL ,
    additional_charge INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (_date)
);

